CHANGELOG.md, README.md, conf/test.config, main.nf, nextflow.config
- `main.nf`: Copied the DSL2 pggb workflow from https://github.com/pangenome/pggb/pull/20 into this one. Currently we are ignoring the `nf-core` way to handle input parameters, software versions, etc. This will change in the future.
- `nextflow.config`: Set default container to `ghcr.io/pangenome/pggb:latest`
- `README.md`: Describe how developers can test the current state of the pipeline.
- `test.config`: Point to valid test data and update the default container.
I am opening this as a draft in order to compare with https://github.com/nf-core/pangenome/pull/2/files and to discuss a way forward with @heuermh .
=> initial workflow and mini test running

README.md
=> Add table of contributors to credits section

conf/test.config
Forgot to include `conf/test.config` into previous PR. Fixing this now.
=> Fix test.config

nextflow.config
=> Dockerfile

.github/workflows/ci.yml, main.nf
=> Use nextflow.enable.dsl instead of nextflow.preview.dsl

README.md
=> Fixed minimum NF badge in Readme

README.md, docs/usage.md
This PR updates `docs/usage.md`. The listed example command is now correct. Important to have, because this also lands on the web page.
=> update usage example

.github/CONTRIBUTING.md
PR addresses https://github.com/nf-core/tools/pull/812.
=> reflect https://github.com/nf-core/tools/pull/812

README.md
See Slack
Signed-off-by: Zethson <lukas.heumos@posteo.net>
=> update LH affiliations & fix EG affiliations

Dockerfile, environment.yml
=> bump upstream Dockerfile to ghcr.io/pangenome/pggb:202012122000576ef861

main.nf
This ensures, that by default no `odgiViz` or `odgiLayout` are run.
=> fixed --do_viz and --do_layout parameters

main.nf
This PR parallelizes the vg_deconstruct process. If more than one reference path for the `vg` deconstruction process is specified, we scale in parallel :)
=> parallelize vg_deconstruct

.github/workflows/ci.yml, .github/workflows/linting.yml, README.md, main.nf, nextflow.config, nextflow_schema.json
=> Pangenome/optional PAF input

main.nf
=> seqwish_groovey_magic

Dockerfile
Update to the latest PGGB docker image which accelerates the 1D PG-SGD algorithm up to ~8 fold https://github.com/pangenome/odgi/pull/445 and the 2D PG-SGD algorithm up to ~7 fold https://github.com/pangenome/odgi/pull/446.
=> odgi sort/layout power up

Dockerfile
This updates the Dockerfile to reflect the updates in https://github.com/pangenome/pggb/pull/231. Furthermore, one needs to be careful when building a pangenome graph, rather select a shorter `wfmash_segment_length` thane before as was found out in https://github.com/pangenome/pggb/issues/232.
=> update Dockerfile to use the most recent biwflambda update

Dockerfile, assets/multiqc_config.yaml, main.nf
This brings in a new diagnostic visualization in the MultiQC report mirroring https://github.com/pangenome/pggb/pull/233.
=> diagnostic vizzz

.github/workflows/ci.yml, Dockerfile, main.nf, nextflow.config, nextflow_schema.json
This updates the input parameters so it's clearer we want the number of haplotypes. `wfmash` maps better smaller / medium sized sequences. See https://github.com/pangenome/pggb/pull/234.
=>  update wfmash for better short/medium sequence alignment

Dockerfile
integrate gfaffix bugfix https://github.com/pangenome/pggb/pull/236 and wfmash update https://github.com/pangenome/pggb/pull/235 via Dockerfile
=> integrate gfaffix bugfix and wfmash update via Dockerfile

main.nf
This unchops the GFAFfixed graph, bringing in https://github.com/pangenome/pggb/pull/237.
=> unchop the GFAFfixed graph

Dockerfile, main.nf, nextflow.config
This brings in the latest changes from https://github.com/pangenome/pggb/pull/242.
=> update to latest PGGB

main.nf, nextflow.config
This mirrors https://github.com/pangenome/pggb/pull/246/.
=> make the smoothxg step optional

Dockerfile, main.nf
This mirrors https://github.com/pangenome/pggb/pull/250/files.
=> wfmashAlign: filter alignments -p x 0.8

Dockerfile, main.nf
This mirrors https://github.com/pangenome/pggb/pull/249.
=> use iterable smoothxg

Dockerfile
This PR reflects https://github.com/pangenome/pggb/pull/264 and https://github.com/pangenome/pggb/pull/265.
=> update pggb docker image

Dockerfile
This reflects https://github.com/pangenome/pggb/pull/266.
=> updage pggb in Dockerfile

.github/workflows/ci.yml, Dockerfile, README.md, nextflow.config
=> the pipeline now works with all NXF versions

Dockerfile, subworkflows/local/pggb/main.nf
This reflects https://github.com/pangenome/pggb/pull/280
=> update pggb docker

Dockerfile
This reflects https://github.com/pangenome/pggb/pull/282.
=> update Dockerfile to match most recent pggb updates

Dockerfile
This reflects https://github.com/pangenome/pggb/pull/286.
=> update pggb gfaffix

Dockerfile
=> update pggb Dockerfile

conf/test_full.config
=> configure aws full scale test

.github/workflows/awsfulltest.yml, README.md, assets/methods_description_template.yml, conf/base.config, conf/test.config, docs/output.md, docs/usage.md, nextflow.config
=> remove TODOs

CHANGELOG.md, nextflow.config
=> prepare 1.0.0 release

modules.json, modules/nf-core/gfaffix/main.nf, modules/nf-core/multiqc/main.nf, modules/nf-core/samtools/faidx/main.nf, modules/nf-core/samtools/faidx/meta.yml, subworkflows/local/community.nf, subworkflows/local/input_check.nf
=> Update modules gfaffix, MultiQC, samtools/faidx

modules/local/multiqc_community/main.nf, modules/local/paf2net/main.nf, modules/local/vg_deconstruct/main.nf
=> Update `vg deconstruct` to v1.50.1

modules.json, modules/nf-core/custom/dumpsoftwareversions/main.nf, modules/nf-core/smoothxg/main.nf
=> update smoothxg to v0.7.1

nextflow.config, subworkflows/local/pggb.nf
This sets the default `wfmash_chunks` to `null` instead of `1` so that it is clear that we don't do chunks when the parameter is not set at all.
=> make the use of chunks explicit

conf/modules.config, modules/local/vg_deconstruct/main.nf, nextflow.config, nextflow_schema.json
=>  Final pre-release 1.1.0 updates

CHANGELOG.md, nextflow_schema.json
=> Some fixes for the release

modules/local/vg_deconstruct/main.nf
=> bump bcftools to 1.19

README.md
=> add bioRxiv DOI

modules.json, modules/nf-core/smoothxg/environment.yml, modules/nf-core/smoothxg/main.nf, modules/nf-core/smoothxg/meta.yml, modules/nf-core/smoothxg/tests/main.nf.test
=> Update nf-core/smoothxg module to version 0.8.0

nextflow.config
=> make parameter `n_haplotypes` null

.nf-core.yml, nextflow.config
=> Add docs/images to files_unchanged

.nf-core.yml, modules.json, nextflow.config
=> update multiqc to v1.26 to fix i224

modules/nf-core/multiqc/environment.yml, modules/nf-core/multiqc/main.nf, modules/nf-core/multiqc/tests/main.nf.test.snap
=> lost & found

.github/workflows/ci.yml, .github/workflows/download_pipeline.yml, .nf-core.yml, CITATIONS.md, README.md, nextflow.config, ro-crate-metadata.json, subworkflows/local/utils_nfcore_pangenome_pipeline/main.nf, workflows/pangenome.nf
Addresses merge conflicts in #225
=> Merging template updates for 3.1.2

modules/local/vg_deconstruct/main.nf
=> update pggb docker to contain vg v1.62

modules/local/multiqc_community/environment.yml, modules/local/multiqc_community/main.nf, modules/local/multiqc_community/meta.yml, workflows/pangenome.nf
This basically works, but the MultiQC config given does not. I just realized the config for the nf-core module does not work anymore, either. I suppose since the template update.
=> update local module multiqc_community to v1.25

README.md
=> Resolve merge conflicts

nextflow.config
=> Fix 1.1.3 release lint error(s)
